[tool.ruff]
target-version = "py311"
line-length = 79
extend-select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "W",  # pycodestyle warnings
    "C90",  # mccabe complexity
    "I",  # isort
    "UP",  # pyupgrade
]
exclude = ["alembic/versions"]

[tool.ruff.lint]
preview = true
fix = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
